services:
  # Service for PostgreSQL database
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Username for the PostgreSQL database
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Password for the PostgreSQL user
      POSTGRES_DB: ${POSTGRES_DB} # Name of the PostgreSQL database
    ports:
      - "5432:5432" # Expose port 5432 for PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for PostgreSQL data
      - ./init-keycloak.sql:/docker-entrypoint-initdb.d/init-keycloak.sql # Keycloak database initialization script
    networks:
      - task_network

  # Service for Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN} # Keycloak admin username
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD} # Keycloak admin password
      KC_DB: ${KC_DB} # Database type (PostgreSQL)
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak # Keycloak database URL
      KC_DB_USERNAME: ${POSTGRES_USER} # Username for Keycloak database
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD} # Password for Keycloak database

    ports:
      - "8585:8585" # Expose port 8585 for Keycloak
    depends_on:
      - postgres-db # Dependency on the PostgreSQL service
    networks:
      - task_network
    command: start-dev --http-port 8585 --hostname-strict=false

  # Service for your application (commented out temporarily)
#  app:
#    build:
#      context: ../
#    container_name: task-mgt-app
#    environment:
#      API_SECRET: "${API_SECRET}"
#      POSTGRES_USER: "${POSTGRES_USER}"
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#    ports:
#      - "8081:8081"
#    depends_on:
#      postgres-db:
#        condition: service_started
#    networks:
#      - task_network

volumes:
  postgres_data:
    external: true

networks:
  task_network:
    name: task_network